create table "apartment" (
                             "id" bigint generated by default as identity,
                             "area" numeric(19,2),
                             "description" varchar(255),
                             "name" varchar(255),
                             "currency" varchar(255),
                             "price" numeric(19,2),
                             "owner_id" bigint,
                             primary key ("id")
);
create table "lessor" (
                          "id" bigint generated by default as identity,
                          "name" varchar(255),
                          primary key ("id")
);
create table "reservation" (
                               "id" bigint generated by default as identity,
                               "currency" varchar(255),
                               "price" numeric(19,2),
                               "end_date" date,
                               "start_date" date,
                               "apartment_id" bigint,
                               "tenant_id" bigint,
                               primary key ("id")
);
create table "tenant" (
                          "id" bigint generated by default as identity,
                          "name" varchar(255),
                          primary key ("id")
);

alter table "apartment"
    add constraint "FK_Owner"
        foreign key ("owner_id")
            references "lessor";

alter table "reservation"
    add constraint "FK_Apartment"
        foreign key ("apartment_id")
            references "apartment";

alter table "reservation"
    add constraint "FK_Tenant"
        foreign key ("tenant_id")
            references "tenant";
